export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea')
    textarea.value = text
    textarea.style.position = 'fixed'
    textarea.style.opacity = '0'
    document.body.appendChild(textarea)
    textarea.select()
    document.execCommand('copy')
    document.body.removeChild(textarea)
    return true
  }
}

export function buildExportText(sections: {
  rewrittenBullets?: Array<{ original: string; rewritten: string; incorporatedKeywords: string[] }>
  coverLetter?: string | null
  overallScore?: number | null
  afterOverallScore?: number | null
  missingKeywords?: Array<{ keyword: string }>
}): string {
  const lines: string[] = []

  lines.push('═══════════════════════════════════════')
  lines.push('  COVERYOURATS — OPTIMIZATION REPORT')
  lines.push('═══════════════════════════════════════')
  lines.push('')

  if (sections.overallScore !== null && sections.overallScore !== undefined) {
    lines.push(`MATCH SCORE: ${sections.overallScore}%`)
    if (sections.afterOverallScore !== null && sections.afterOverallScore !== undefined) {
      const improvement = sections.afterOverallScore - sections.overallScore
      lines.push(`OPTIMIZED SCORE: ${sections.afterOverallScore}% (+${improvement})`)
    }
    lines.push('')
  }

  if (sections.rewrittenBullets && sections.rewrittenBullets.length > 0) {
    lines.push('───────────────────────────────────────')
    lines.push('  REWRITTEN BULLETS')
    lines.push('───────────────────────────────────────')
    lines.push('')
    for (const bullet of sections.rewrittenBullets) {
      lines.push(`BEFORE: ${bullet.original}`)
      lines.push(`AFTER:  ${bullet.rewritten}`)
      if (bullet.incorporatedKeywords.length > 0) {
        lines.push(`ADDED:  ${bullet.incorporatedKeywords.join(', ')}`)
      }
      lines.push('')
    }
  }

  if (sections.coverLetter) {
    lines.push('───────────────────────────────────────')
    lines.push('  COVER LETTER')
    lines.push('───────────────────────────────────────')
    lines.push('')
    lines.push(sections.coverLetter)
    lines.push('')
  }

  if (sections.missingKeywords && sections.missingKeywords.length > 0) {
    lines.push('───────────────────────────────────────')
    lines.push('  STILL MISSING KEYWORDS')
    lines.push('───────────────────────────────────────')
    lines.push('')
    lines.push(sections.missingKeywords.map((k) => k.keyword).join(', '))
    lines.push('')
  }

  lines.push('═══════════════════════════════════════')
  lines.push('  Generated by CoverYourATS')
  lines.push('═══════════════════════════════════════')

  return lines.join('\n')
}
