import type { RewrittenBullet, CategoryScore } from '../../types'

interface PdfExportData {
  overallScore: number | null
  afterOverallScore: number | null
  categoryScores: CategoryScore[]
  rewrittenBullets: RewrittenBullet[]
  coverLetter: string | null
  missingKeywords: Array<{ keyword: string; category: string }>
}

export async function exportToPdf(data: PdfExportData): Promise<void> {
  // Lazy-load jsPDF
  const { default: jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  const contentWidth = pageWidth - margin * 2
  let y = 20

  const checkPageBreak = (needed: number) => {
    if (y + needed > 280) {
      doc.addPage()
      y = 20
    }
  }

  // Title
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('CoverYourATS — Optimization Report', margin, y)
  y += 10

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated ${new Date().toLocaleDateString()}`, margin, y)
  doc.setTextColor(0, 0, 0)
  y += 12

  // Scores
  if (data.overallScore !== null) {
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Match Score', margin, y)
    y += 7

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Before: ${data.overallScore}%`, margin, y)
    if (data.afterOverallScore !== null) {
      const improvement = data.afterOverallScore - data.overallScore
      doc.text(
        `After: ${data.afterOverallScore}% (+${improvement})`,
        margin + 50,
        y
      )
    }
    y += 8

    // Category breakdown
    if (data.categoryScores.length > 0) {
      for (const cs of data.categoryScores) {
        if (cs.total === 0) continue
        checkPageBreak(6)
        const label = cs.category.replace('_', ' ').toUpperCase()
        doc.setFontSize(9)
        doc.text(
          `${label}: ${cs.matched.length}/${cs.total} (${cs.score}%)`,
          margin + 4,
          y
        )
        y += 5
      }
      y += 5
    }
  }

  // Rewritten Bullets
  if (data.rewrittenBullets.length > 0) {
    checkPageBreak(15)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Rewritten Resume Bullets', margin, y)
    y += 8

    for (const bullet of data.rewrittenBullets) {
      checkPageBreak(25)

      doc.setFontSize(9)
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(150, 50, 50)
      const origLines = doc.splitTextToSize(`Before: ${bullet.original}`, contentWidth - 4)
      doc.text(origLines, margin + 2, y)
      y += origLines.length * 4 + 1

      doc.setFont('helvetica', 'normal')
      doc.setTextColor(30, 120, 30)
      const rewriteLines = doc.splitTextToSize(`After: ${bullet.rewritten}`, contentWidth - 4)
      doc.text(rewriteLines, margin + 2, y)
      y += rewriteLines.length * 4 + 1

      if (bullet.incorporatedKeywords.length > 0) {
        doc.setTextColor(80, 80, 80)
        doc.setFontSize(8)
        doc.text(
          `Keywords added: ${bullet.incorporatedKeywords.join(', ')}`,
          margin + 2,
          y
        )
        y += 4
      }

      doc.setTextColor(0, 0, 0)
      y += 4
    }
  }

  // Cover Letter
  if (data.coverLetter) {
    checkPageBreak(15)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text('Generated Cover Letter', margin, y)
    y += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const clLines = doc.splitTextToSize(data.coverLetter, contentWidth)
    for (const line of clLines) {
      checkPageBreak(5)
      doc.text(line, margin, y)
      y += 4.5
    }
    y += 6
  }

  // Missing Keywords
  if (data.missingKeywords.length > 0) {
    checkPageBreak(15)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Still Missing Keywords', margin, y)
    y += 8

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const kwText = data.missingKeywords.map((k) => k.keyword).join(', ')
    const kwLines = doc.splitTextToSize(kwText, contentWidth)
    for (const line of kwLines) {
      checkPageBreak(5)
      doc.text(line, margin, y)
      y += 4.5
    }
  }

  // Footer
  checkPageBreak(15)
  y += 10
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by CoverYourATS — Resume Keyword Optimizer', margin, y)

  doc.save('coveryourats-report.pdf')
}
